version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Python ML Service
  mlapi:
    build: 
      context: ./FraudDetection.MLApi
    container_name: mlapi
    ports:
      - "8000:5000" # Mapped to 8000 to avoid conflict

  # .NET Backend API
  backend-api:
    build:
      # FIX: Point to the parent folder containing the API
      context: ./FraudDetection.Processor
      # FIX: Point to the Dockerfile inside the API folder
      dockerfile: FraudDetection.API/Dockerfile
    container_name: backend-api
    depends_on:
      - kafka
      - mlapi
    ports:
      - "5000:8080"
    environment:
      - Kafka__BootstrapServers=kafka:29092
      - ApiUrl=http://mlapi:5000

  # React Frontend
  frontend:
    build:
      context: ./FraudDetection.Web
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-api