version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      # IMPORTANT: 
      # - localhost:9092 is for YOU (external)
      # - kafka:29092 is for the .NET App (internal)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # The Python Brain
  mlapi:
    build: 
      context: ./FraudDetection.MLApi
    container_name: mlapi
    ports:
      - "5000:5000"

  # The .NET Muscle
  processor:
    build:
      context: ./FraudDetection.Processor
      dockerfile: Dockerfile
    container_name: processor
    depends_on:
      - kafka
      - mlapi
    environment:
      # Overriding the C# settings here!
      - Kafka__BootstrapServers=kafka:29092
      - ApiUrl=http://mlapi:5000